### ISSUE TITLE
Status of Project

### ISSUE THREAD

**Issue by ghachey** [zbrad/EmacsKeys#5]
Hi,

Is this project active? I've recently had to work with VS and C#. But I really want my Emacs bindings. Can it work with Community edition of VS 2015?

**Comment by zbrad** [comment]
Well it is still active.   I usually use it with pro, so I haven't tested it with community.   Can you use other VSIX extensions with community?   If so, then it should just work.

**Comment by ghachey** [comment]
Thanks. I saw this "(the Express editions do not support extensions)" on the extension page. But then I assume with VS 2015 Community edition it _does_ support extensions as I got it to work. I did have to manually copy the Emacs.vsk as described in the solution comments at http://stackoverflow.com/questions/13884953/emacs-keybindings-in-visual-studio-2012-or-2013/14087731#14087731

**Comment by zbrad** [comment]
cool!   I really need to change the installation to either an MSI (which can copy the vsk), or else avoid the VSK solution entirely and just use the binding settings files.
