### ISSUE TITLE
Centering text not completely working

### ISSUE THREAD

**Issue by ghachey** [zbrad/EmacsKeys#8]
Centering text works with Ctrl-L but it does not have the full Emacs behavior: it can only put the cursor in the middle. Clicking Ctrl-L in Emacs will first put the cursor in the middle of the editor, then at the top then at the bottom before starting back and putting in the middle, etc. Is that something easy to add or not in there because of how VS works?

**Comment by ywabiko** [comment]
Actually I prefer the current behavior that aligns with "original" Emacs. What you mention above is a recent recenter introduced in Emacs 23 or so and is fairly annoying to me:)

**Comment by zbrad** [comment]
yeah, I think it's actually correct with original centering.
